"""init tables

Revision ID: 3c4794d0aec8
Revises:
Create Date: 2025-11-15 14:58:31.772537

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3c4794d0aec8"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index("ix_interests_name", "interests", ["name"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("pass_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("role", sa.Enum("user", "admin", name="role_enum"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index("ix_users_role", "users", ["role"], unique=False)
    op.create_table(
        "chats",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("direct_a", sa.String(length=36), nullable=False),
        sa.Column("direct_b", sa.String(length=36), nullable=False),
        sa.Column("type", sa.Enum("direct", name="chat_type_enum"), nullable=False),
        sa.CheckConstraint("direct_a <> direct_b", name="chk_chat_not_self"),
        sa.ForeignKeyConstraint(["direct_a"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["direct_b"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_chats_type", "chats", ["type"], unique=False)
    op.create_index(
        "uq_chats_direct_pair", "chats", ["direct_a", "direct_b"], unique=True
    )
    op.create_table(
        "profile",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("full_name", sa.String(length=120), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("about", sa.Text(), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column(
            "visibility",
            sa.Enum("all", "matched", "none", name="profile_vis_enum"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index("ix_profile_full_name", "profile", ["full_name"], unique=False)
    op.create_index("ix_profiles_city", "profile", ["city"], unique=False)
    op.create_table(
        "user_interests",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("interest_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["interest_id"], ["interests.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "interest_id"),
    )
    op.create_index(
        "ix_user_interests_interest_user",
        "user_interests",
        ["interest_id", "user_id"],
        unique=False,
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("chat_id", sa.String(length=36), nullable=False),
        sa.Column("author_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_messages_author", "messages", ["author_id"], unique=False)
    op.create_index(
        "ix_messages_chat_created", "messages", ["chat_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_messages_chat_created", table_name="messages")
    op.drop_index("ix_messages_author", table_name="messages")
    op.drop_table("messages")
    op.drop_index("ix_user_interests_interest_user", table_name="user_interests")
    op.drop_table("user_interests")
    op.drop_index("ix_profiles_city", table_name="profile")
    op.drop_index("ix_profile_full_name", table_name="profile")
    op.drop_table("profile")
    op.drop_index("uq_chats_direct_pair", table_name="chats")
    op.drop_index("ix_chats_type", table_name="chats")
    op.drop_table("chats")
    op.drop_index("ix_users_role", table_name="users")
    op.drop_table("users")
    op.drop_index("ix_interests_name", table_name="interests")
    op.drop_table("interests")
    # ### end Alembic commands ###
