"""Update profile, interests, and chat models

Revision ID: 5b19217e678c
Revises: 3c4794d0aec8
Create Date: 2025-12-05 11:07:41.065001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b19217e678c'
down_revision: Union[str, Sequence[str], None] = '3c4794d0aec8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interests', sa.Column('group', sa.String(length=120), server_default='Другое', nullable=False))
    op.create_index('ix_interests_group', 'interests', ['group'], unique=False)
    op.add_column('profile', sa.Column('first_name', sa.String(length=40), nullable=True))
    op.add_column('profile', sa.Column('last_name', sa.String(length=40), nullable=True))
    op.add_column('profile', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('profile', sa.Column('telegram', sa.String(length=120), nullable=True))
    op.drop_index(op.f('ix_profile_full_name'), table_name='profile')
    op.create_index('ix_profile_first_name', 'profile', ['first_name'], unique=False)
    op.create_index('ix_profile_last_name', 'profile', ['last_name'], unique=False)
    op.drop_column('profile', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('full_name', sa.VARCHAR(length=120), nullable=True))
    op.drop_index('ix_profile_last_name', table_name='profile')
    op.drop_index('ix_profile_first_name', table_name='profile')
    op.create_index(op.f('ix_profile_full_name'), 'profile', ['full_name'], unique=False)
    op.drop_column('profile', 'telegram')
    op.drop_column('profile', 'email')
    op.drop_column('profile', 'last_name')
    op.drop_column('profile', 'first_name')
    op.drop_index('ix_interests_group', table_name='interests')
    op.drop_column('interests', 'group')
    # ### end Alembic commands ###
