"""add_user_interactions

Revision ID: bf64c291d25e
Revises: 5b19217e678c
Create Date: 2025-12-16 14:31:37.758880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf64c291d25e'
down_revision: Union[str, Sequence[str], None] = '5b19217e678c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_interactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('target_user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.Enum('pass_', 'like', 'view', name='interaction_action_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interactions_user_action', 'user_interactions', ['user_id', 'action'], unique=False)
    op.create_index('ix_interactions_user_target', 'user_interactions', ['user_id', 'target_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_interactions_user_target', table_name='user_interactions')
    op.drop_index('ix_interactions_user_action', table_name='user_interactions')
    op.drop_table('user_interactions')
    # ### end Alembic commands ###
